services:
  playwright-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-vnc
    ports:
      - "5900:5900" # VNC
      - "6080:6080" # noVNC
      - "2222:2222" # playwright server
    volumes:
      - ./data:/app/data
